window.CALENDAR_STYLES = {
    minimal: {
        label: 'Minimal',
        desc: 'White',
        swatch: 'linear-gradient(180deg, #ffffff, #f1f3f4)',
        heroType: 'minimal',
        font: "'Google Sans', Roboto, sans-serif",
        appBar: '#ffffff',
        appBarText: '#202124',
        body: '#ffffff',
        monthText: '#202124',
        weekday: '#5f6368',
        day: '#202124',
        dayOther: '#bdc1c6',
        todayBg: '#202124',
        todayText: '#ffffff',
        eventBg: '#f8f9fa',
        eventBorder: '#dadce0',
        eventText: '#202124',
        navBg: '#ffffff',
        navIcon: '#5f6368',
        navBorder: '#e8eaed',
        fab: '#202124',
        fabText: '#ffffff',
        dark: false,
    },
    starwars: {
        label: 'Star Wars',
        desc: 'Space opera',
        swatch: 'radial-gradient(circle, #FFE81F 0%, #1a1a2e 40%, #000 100%)',
        heroType: 'starwars',
        font: "'Roboto', sans-serif",
        titleFont: "'Star Jedi', sans-serif",
        appBar: '#0a0a0f',
        appBarText: '#FFE81F',
        body: '#0a0a0f',
        monthText: '#FFE81F',
        weekday: '#888',
        day: '#ccc',
        dayOther: '#444',
        todayBg: '#FFE81F',
        todayText: '#000',
        eventBg: 'rgba(20,20,30,0.95)',
        eventBorder: '#FFE81F',
        eventText: '#FFE81F',
        navBg: '#0a0a0f',
        navIcon: '#888',
        navBorder: '#222',
        fab: '#FFE81F',
        fabText: '#000',
        dark: true,
    },
    tron: {
        label: 'Tron',
        desc: 'Neon grid',
        swatch: 'linear-gradient(180deg, #000 0%, #001a1a 100%)',
        heroType: 'tron',
        font: "'Google Sans', Roboto, sans-serif",
        appBar: '#000000',
        appBarText: '#00fff2',
        body: '#000000',
        monthText: '#00fff2',
        weekday: '#007770',
        day: '#00fff2',
        dayOther: '#003333',
        todayBg: '#00fff2',
        todayText: '#000',
        eventBg: 'rgba(0,20,20,0.9)',
        eventBorder: '#00fff2',
        eventText: '#00fff2',
        navBg: '#000000',
        navIcon: '#007770',
        navBorder: '#003333',
        fab: '#00fff2',
        fabText: '#000',
        dark: true,
    },
    nebula: {
        label: 'Nebula',
        desc: 'Cosmic',
        swatch: 'radial-gradient(ellipse, #ec4899, #6366f1, #0f172a)',
        heroType: 'nebula',
        font: "'Google Sans', Roboto, sans-serif",
        appBar: 'rgba(15,10,40,0.95)',
        appBarText: '#e9d5ff',
        body: '#0f0a28',
        monthText: '#f0abfc',
        weekday: '#a78bfa',
        day: '#e9d5ff',
        dayOther: '#4c1d95',
        todayBg: '#a855f7',
        todayText: '#fff',
        eventBg: 'rgba(30,15,60,0.9)',
        eventBorder: '#c084fc',
        eventText: '#f3e8ff',
        navBg: '#0f0a28',
        navIcon: '#a78bfa',
        navBorder: '#312e81',
        fab: '#a855f7',
        fabText: '#fff',
        dark: true,
    },
    coder: {
        label: 'Code Nerd',
        desc: 'Terminal',
        swatch: 'linear-gradient(180deg, #0d1117, #161b22)',
        heroType: 'coder',
        font: "ui-monospace, 'Cascadia Code', 'Fira Code', monospace",
        appBar: '#0d1117',
        appBarText: '#58a6ff',
        body: '#0d1117',
        monthText: '#7ee787',
        weekday: '#484f58',
        day: '#c9d1d9',
        dayOther: '#30363d',
        todayBg: '#238636',
        todayText: '#fff',
        eventBg: '#161b22',
        eventBorder: '#30363d',
        eventText: '#c9d1d9',
        navBg: '#0d1117',
        navIcon: '#484f58',
        navBorder: '#21262d',
        fab: '#238636',
        fabText: '#fff',
        dark: true,
    },
};
